# Generated by Django 5.0.3 on 2024-03-18 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentsChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('link_to_avatar', models.TextField()),
                ('gender', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=1)),
                ('birthdate', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('children', models.ManyToManyField(through='gallery.ParentsChildren', to='gallery.person')),
                ('father', models.ForeignKey(limit_choices_to={'gender': 'm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_to', to='gallery.person')),
                ('mother', models.ForeignKey(limit_choices_to={'gender': 'f'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_to', to='gallery.person')),
                ('spouse', models.ForeignKey(limit_choices_to={'gender__ne': models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=1)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_spouse', to='gallery.person')),
            ],
        ),
        migrations.AddField(
            model_name='parentschildren',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_to', to='gallery.person'),
        ),
        migrations.AddField(
            model_name='parentschildren',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_to', to='gallery.person'),
        ),
        migrations.CreateModel(
            name='AlbumCircles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_for_album', to='gallery.album')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums_for_circle', to='gallery.person')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='circle',
            field=models.ManyToManyField(through='gallery.AlbumCircles', to='gallery.person'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_image', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=75)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('album_id', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.person')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.photo')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_in_album', to='gallery.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_for_photo', to='gallery.photo')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(through='gallery.AlbumPhotos', to='gallery.photo'),
        ),
        migrations.CreateModel(
            name='PhotoLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_person', to='gallery.person')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_for_photo', to='gallery.photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(related_name='photos_liked_by', through='gallery.PhotoLikes', to='gallery.person'),
        ),
        migrations.CreateModel(
            name='PhotoPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_with_person', to='gallery.person')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_in_photo', to='gallery.photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='people',
            field=models.ManyToManyField(related_name='photos_with', through='gallery.PhotoPerson', to='gallery.person'),
        ),
        migrations.CreateModel(
            name='PhotoTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_for_photo', to='gallery.photo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_with_tag', to='gallery.tag')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(through='gallery.PhotoTags', to='gallery.tag'),
        ),
    ]
