# Generated by Django 5.0.3 on 2024-03-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(limit_choices_to=models.Q(('gender', 'f')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_spouse', to='gallery.person'),
        ),
    ]
