# Generated by Django 5.0.3 on 2024-03-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_person_spouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='link_to_avatar',
            field=models.TextField(null=True),
        ),
    ]
