# Generated by Django 5.0.3 on 2024-03-18 10:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_person_birthdate_alter_person_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_to', to='gallery.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='link_to_avatar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'f'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_to', to='gallery.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('gender', 'f')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_spouse', to='gallery.person'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.person'),
        ),
    ]
